<a href="https://colab.research.google.com/github/anggitsetiawan10/HTML-Dasar/blob/main/Python_Naive_Bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, accuracy_score


In [12]:
dataset = pd.read_excel('/content/sample_data/Golf.xlsx')
dataset.head()

No   Outlook  Temperature  Humidity  Windy Play
0   1     sunny           85        85  False   no
1   2     sunny           80        90   True   no
2   3  overcast           83        78  False  yes
3   4      rain           70        96  False  yes
4   5      rain           68        80  False  yes

In [13]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   No           14 non-null     int64 
 1   Outlook      14 non-null     object
 2   Temperature  14 non-null     int64 
 3   Humidity     14 non-null     int64 
 4   Windy        14 non-null     bool  
 5   Play         14 non-null     object
dtypes: bool(1), int64(3), object(2)
memory usage: 702.0+ bytes


In [14]:
dataset.empty

False

In [15]:
en = LabelEncoder()
dataset['Play'] = en.fit_transform(dataset['Play'])
dataset.head()

No   Outlook  Temperature  Humidity  Windy  Play
0   1     sunny           85        85  False     0
1   2     sunny           80        90   True     0
2   3  overcast           83        78  False     1
3   4      rain           70        96  False     1
4   5      rain           68        80  False     1

In [16]:
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [17]:
x

array([[1, 'sunny', 85, 85, False],
       [2, 'sunny', 80, 90, True],
       [3, 'overcast', 83, 78, False],
       [4, 'rain', 70, 96, False],
       [5, 'rain', 68, 80, False],
       [6, 'rain', 65, 70, True],
       [7, 'overcast', 64, 65, True],
       [8, 'sunny', 72, 95, False],
       [9, 'sunny', 69, 70, False],
       [10, 'rain', 75, 80, False],
       [11, 'sunny', 75, 70, True],
       [12, 'overcast', 72, 90, True],
       [13, 'overcast', 81, 75, False],
       [14, 'rain', 71, 80, True]], dtype=object)

In [18]:
y

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

In [19]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

print("x_train = ", len(x_train))
print("x_test = ", len(x_test))
print("y_train = ", len(y_train))
print("y_test = ", len(y_test))

x_train =  11
x_test =  3
y_train =  11
y_test =  3


In [22]:
!pip install scikit-learn
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
# Asumsikan 'dataset' adalah DataFrame pandas Anda

# Ekstrak fitur dan variabel target
x = dataset.iloc[:, :-1]  # Pertahankan sebagai DataFrame untuk OneHotEncoder
y = dataset.iloc[:, -1].values

# Bagi data menjadi set pelatihan dan pengujian
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

# Buat objek OneHotEncoder
encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore') # sparse=False untuk array numpy

# Sesuaikan encoder pada data pelatihan dan transformasikan data pelatihan dan pengujian
x_train_encoded = encoder.fit_transform(x_train[['Outlook', 'Temperature','Humidity','Windy']]) # Asumsikan 'Outlook' adalah kolom kategorikal Anda dengan 'overcast', 'sunny'
x_test_encoded = encoder.transform(x_test[['Outlook', 'Temperature','Humidity','Windy']])

# Buat objek StandardScaler
sc = StandardScaler()

# Sesuaikan scaler pada data pelatihan yang dikodekan dan transformasikan data pelatihan dan pengujian
x_train = sc.fit_transform(x_train_encoded)
x_test = sc.transform(x_test_encoded)

In [23]:
x_train

array([[ 1.63299316, -0.75592895, -0.75592895, -0.31622777, -0.31622777,
        -0.31622777,  2.12132034, -0.47140452, -0.31622777, -0.31622777,
        -0.31622777, -0.31622777, -0.47140452, -0.31622777, -0.31622777,
        -0.47140452, -0.31622777,  2.12132034, -0.31622777, -0.31622777,
        -1.09544512,  1.09544512],
       [ 1.63299316, -0.75592895, -0.75592895, -0.31622777, -0.31622777,
        -0.31622777, -0.47140452, -0.47140452, -0.31622777, -0.31622777,
         3.16227766, -0.31622777, -0.47140452, -0.31622777,  3.16227766,
        -0.47140452, -0.31622777, -0.47140452, -0.31622777, -0.31622777,
         0.91287093, -0.91287093],
       [-0.61237244,  1.32287566, -0.75592895, -0.31622777, -0.31622777,
         3.16227766, -0.47140452, -0.47140452, -0.31622777, -0.31622777,
        -0.31622777, -0.31622777, -0.47140452, -0.31622777, -0.31622777,
         2.12132034, -0.31622777, -0.47140452, -0.31622777, -0.31622777,
        -1.09544512,  1.09544512],
       [-0.61237244

In [24]:
x_test

array([[-0.61237244, -0.75592895,  1.32287566, -0.31622777, -0.31622777,
        -0.31622777, -0.47140452, -0.47140452, -0.31622777, -0.31622777,
        -0.31622777, -0.31622777,  2.12132034, -0.31622777, -0.31622777,
        -0.47140452, -0.31622777, -0.47140452, -0.31622777, -0.31622777,
         0.91287093, -0.91287093],
       [ 1.63299316, -0.75592895, -0.75592895, -0.31622777, -0.31622777,
        -0.31622777, -0.47140452, -0.47140452, -0.31622777, -0.31622777,
        -0.31622777, -0.31622777, -0.47140452, -0.31622777, -0.31622777,
        -0.47140452, -0.31622777, -0.47140452, -0.31622777, -0.31622777,
        -1.09544512,  1.09544512],
       [-0.61237244,  1.32287566, -0.75592895, -0.31622777, -0.31622777,
        -0.31622777, -0.47140452, -0.47140452, -0.31622777, -0.31622777,
        -0.31622777, -0.31622777, -0.47140452, -0.31622777, -0.31622777,
         2.12132034, -0.31622777, -0.47140452, -0.31622777, -0.31622777,
         0.91287093, -0.91287093]])

In [25]:
y_train

array([1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1])

In [26]:
y_test

array([1, 1, 1])

In [27]:
classifier = GaussianNB()
classifier.fit(x_train, y_train)

GaussianNB()

In [28]:
y_pred = classifier.predict(x_test)
y_pred

array([0, 1, 0])

In [29]:
classifier.predict_proba(x_test)

array([[1.00000000e+00, 3.17911595e-10],
       [0.00000000e+00, 1.00000000e+00],
       [9.99999996e-01, 3.80894172e-09]])

In [30]:
cm = confusion_matrix(y_test, y_pred)
print(cm)


[[0 0]
 [2 1]]


In [32]:
# Impor fungsi yang diperlukan
from sklearn.metrics import classification_report

# Sekarang Anda dapat menggunakan fungsi classification_report
akurasi = classification_report(y_test, y_pred)
print(akurasi)

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       1.00      0.33      0.50         3

    accuracy                           0.33         3
   macro avg       0.50      0.17      0.25         3
weighted avg       1.00      0.33      0.50         3



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [34]:
akurasi = accuracy_score(y_test, y_pred)
print("Tingkat akurasi : %d persen"%(akurasi*100))

Tingkat akurasi : 33 persen


In [36]:
ydata = pd.DataFrame()
ydata['y_test'] = pd.DataFrame(y_test)
ydata['y_pred'] = pd.DataFrame(y_pred)
ydata

y_test  y_pred
0       1       0
1       1       1
2       1       0

In [37]:
ydata.to_excel('HasilPrediksi.xlsx', index=False)